[package]
name = "web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]  # cdylib for WASM, rlib for Rust linking

[dependencies]
wasm-bindgen = "0.2"
semitile_core = { path = "../semitile_core" }
